services:
  solara-music:
    image: xiaosahuogui/solara-music:latest 
    container_name: solara-music
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SOLARA_PASSWORD=Solara123  # 修改为你的密码
      - DOWNLOAD_DIR=/download  # 容器内的下载目录
    volumes:
      - ./logs:/app/logs
      - ./downloads:/download  # 下载目录映射
